# Generated by Django 3.2.5 on 2021-08-10 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название документа')),
                ('doc_author', models.CharField(max_length=50, verbose_name='Автор')),
                ('approval_date', models.DateField(default=datetime.date.today, verbose_name='Дата утверждения')),
                ('doc_url', models.CharField(max_length=250, verbose_name='Ссылка на документ')),
                ('note', models.CharField(max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
