# Generated by Django 4.0 on 2022-01-11 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211229_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_source',
            field=models.CharField(default='АСДОУ', max_length=250, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='note',
            field=models.CharField(default='НЕТ', max_length=250, verbose_name='Комментарий, номенкл. номер'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='revision_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата пересмотра'),
        ),
    ]
